name: "Infracost Environment Diff"
description: "Generate Infracost diff for a specific environment"
inputs:
  environment:
    required: true
    description: "Environment folder to analyze"
runs:
  using: "composite"
  steps:
    - name: Generate Infracost diff (${{ inputs.environment }})
      shell: bash
      run: |
        cd ${{ inputs.environment }}
        infracost diff --path=. \
                      --format=json \
                      --compare-to=/tmp/infracost-base-${{ inputs.environment }}.json \
                      --out-file=/tmp/infracost-${{ inputs.environment }}.json

    - name: Output Infracost ${{ inputs.environment }} Summary
      shell: bash
      run: |
        infracost output --path=/tmp/infracost-${{ inputs.environment }}.json \
                --format=table
        echo "## Infracost ${{ inputs.environment }} Summary" >> $GITHUB_STEP_SUMMARY
        echo "$(infracost output --path=/tmp/infracost-${{ inputs.environment }}.json --format=markdown --show-skipped)" >> $GITHUB_STEP_SUMMARY
