name: "Infracost Environment Baseline"
description: "Generate Infracost baseline for a specific environment"
inputs:
  environment:
    required: true
    description: "Environment folder to analyze"
runs:
  using: "composite"
  steps:
    - name: Generate Infracost cost estimate baseline (${{ inputs.environment }})
      shell: bash
      run: |
        cd ${{ inputs.environment }}
        infracost breakdown --path=. \
                          --format=json \
                          --out-file=/tmp/infracost-base-${{ inputs.environment }}.json
