grafana:
  grafana.ini:
    auth.generic_oauth:
      name: Auth0
      enabled: true
      allow_sign_up: true
      scopes: openid profile email groups
      auth_url: https://${auth0_tenant}/authorize
      token_url: https://${auth0_tenant}/oauth/token
      api_url: https://${auth0_tenant}/userinfo
      use_pkce: true
      use_refresh_token: true
      groups_attribute_path: '"https://${grafana_subdomain}/groups"'
      role_attribute_path: 'contains("https://${grafana_subdomain}/groups"[*], ''grafana-admin'') && ''GrafanaAdmin'' || contains("https://${grafana_subdomain}/groups"[*], ''grafana-editor'') && ''Editor'' || ''Viewer'''
      allow_assign_grafana_admin: true
  envValueFrom:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
      secretKeyRef:
        name: grafana-oauth-secret
        key: client_id
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
      secretKeyRef:
        name: grafana-oauth-secret
        key: client_secret
