grafana:
  grafana.ini:
    auth.generic_oauth:
      name: Cognito
      enabled: true
      allow_sign_up: true
      scopes: openid email
      auth_url: https://${oauth_tenant}/oauth2/authorize
      token_url: https://${oauth_tenant}/oauth2/token
      api_url: https://${oauth_tenant}/oauth2/userInfo
      use_pkce: true
      use_refresh_token: true
      email_attribute_path: email
      groups_attribute_path: cognito:groups
      role_attribute_path: "contains(groups[*], 'admin') && 'GrafanaAdmin' || 'Viewer'"
      allow_assign_grafana_admin: true
  envValueFrom:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
      secretKeyRef:
        name: grafana-oauth-secret
        key: client_id
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
      secretKeyRef:
        name: grafana-oauth-secret
        key: client_secret
