name: Terraform Cost Analysis

on:
  workflow_call:
    inputs:
      is_pr:
        description: "Whether this is running in a PR context"
        required: true
        type: boolean
    secrets:
      INFRACOST_API_KEY:
        required: true

jobs:
  infracost:
    name: Infracost
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Use the correct setup action from the infracost/actions repository
      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      # When running on a PR, checkout the base branch to compare against
      - name: Checkout base branch for comparison (PR only)
        if: inputs.is_pr
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
          git checkout -b base refs/remotes/origin/${{ github.base_ref }}
          git checkout ${{ github.ref }}
        shell: bash

      # Calculate baseline costs for dev environment (PR only)
      - name: Generate dev environment baseline
        if: inputs.is_pr
        run: |
          cd ./dev
          infracost breakdown --path=. --terraform-workspace=dev --terraform-var-file=dev.auto.tfvars --format=json --out-file=/tmp/infracost-base-dev.json
        shell: bash

      # Calculate baseline costs for shared environment (PR only)
      - name: Generate shared environment baseline
        if: inputs.is_pr
        run: |
          cd ./shared
          infracost breakdown --path=. --terraform-workspace=shared --terraform-var-file=shared.auto.tfvars --format=json --out-file=/tmp/infracost-base-shared.json
        shell: bash

      # Calculate current costs for dev environment
      - name: Generate dev environment current costs
        run: |
          cd ./dev
          infracost breakdown --path=. --terraform-workspace=dev --terraform-var-file=dev.auto.tfvars --format=json --out-file=/tmp/infracost-dev.json
        shell: bash

      # Calculate current costs for shared environment
      - name: Generate shared environment current costs
        run: |
          cd ./shared
          infracost breakdown --path=. --terraform-workspace=shared --terraform-var-file=shared.auto.tfvars --format=json --out-file=/tmp/infracost-shared.json
        shell: bash

      # For PRs, generate the diff between baseline and current
      - name: Generate dev environment diff
        if: inputs.is_pr
        run: infracost diff --path=/tmp/infracost-dev.json --compare-to=/tmp/infracost-base-dev.json --format=json --out-file=/tmp/infracost-diff-dev.json
        shell: bash

      - name: Generate shared environment diff
        if: inputs.is_pr
        run: infracost diff --path=/tmp/infracost-shared.json --compare-to=/tmp/infracost-base-shared.json --format=json --out-file=/tmp/infracost-diff-shared.json
        shell: bash

      # If this is a PR, post a comment showing the cost diff
      - name: Post PR cost diff comment
        if: inputs.is_pr
        run: |
          infracost comment github --path=/tmp/infracost-diff-*.json \
                               --repo=$GITHUB_REPOSITORY \
                               --github-token=${{github.token}} \
                               --pull-request=${{github.event.pull_request.number}} \
                               --behavior=update
        shell: bash

      # For manual runs, output the cost breakdown to the log
      - name: Output dev cost breakdown to log
        if: "!inputs.is_pr"
        run: |
          echo "💰 Dev Environment Cost Breakdown"
          echo "----------------------------------------"
          cat /tmp/infracost-dev.json | jq -r '.projects[] | "Resource: \(.name), Monthly Cost: \(.monthlyCost)"'
          echo "----------------------------------------"
          cat /tmp/infracost-dev.json | jq -r '"Total Monthly Cost: \(.totalMonthlyCost)"'
        shell: bash

      - name: Output shared cost breakdown to log
        if: "!inputs.is_pr"
        run: |
          echo "💰 Shared Environment Cost Breakdown"
          echo "----------------------------------------"
          cat /tmp/infracost-shared.json | jq -r '.projects[] | "Resource: \(.name), Monthly Cost: \(.monthlyCost)"'
          echo "----------------------------------------"
          cat /tmp/infracost-shared.json | jq -r '"Total Monthly Cost: \(.totalMonthlyCost)"'
        shell: bash

      # Generate HTML report for manual runs
      - name: Generate HTML cost report
        if: "!inputs.is_pr"
        run: |
          infracost output --path=/tmp/infracost-*.json --format=html --out-file=/tmp/cost-report.html
        shell: bash
