name: CI pipeline

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.tf"
      - "**/*.tfvars"
      - ".github/workflows/**"
  push:
    branches:
      - main
      - update-ci-workflow
    paths:
      - "**/*.tf"
      - "**/*.tfvars"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  lint:
    name: Format and Lint Check
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: false

      - uses: actions/cache@v4
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ubuntu-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.52.0

      - name: Initialize TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        id: lint
        run: tflint --recursive --format compact
        continue-on-error: false

  # Call reusable workflows for each environment
  validate-dev:
    needs: lint
    uses: ./.github/workflows/tf-env-validate.yml
    with:
      environment: dev
      terraform_version: 1.11.2

  validate-shared:
    needs: lint
    uses: ./.github/workflows/tf-env-validate.yml
    with:
      environment: shared
      terraform_version: 1.11.2

  # Call security scanning workflow
  security-scan:
    needs: [validate-dev, validate-shared]
    uses: ./.github/workflows/tf-security-scan.yml

  # Call cost analysis workflow for pull requests
  cost-analysis:
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
    needs: [validate-dev, validate-shared]
    uses: ./.github/workflows/tf-cost-analysis.yml
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
